[app]
name = "restful_api"
host = "0.0.0.0"
port = "3580"
grpc_host = "0.0.0.0"
grpc_port = "3570"
key  = "this is your app key"

[mysql]
host = "192.168.83.147"
port = "3306"
username = "root"
password = "Tcdn@2007"
database = "restful_api"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"